"""add_chat_participants_and_channel_type

Revision ID: 073c336be0eb
Revises: 26ba675ad404
Create Date: 2025-11-29 14:01:42.046330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073c336be0eb'
down_revision = '26ba675ad404'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collab_channel_participant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['collab_channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collab_channel_participant_channel_id'), 'collab_channel_participant', ['channel_id'], unique=False)
    op.create_index(op.f('ix_collab_channel_participant_driver_id'), 'collab_channel_participant', ['driver_id'], unique=False)
    op.create_index(op.f('ix_collab_channel_participant_user_id'), 'collab_channel_participant', ['user_id'], unique=False)
    op.add_column('collab_channel', sa.Column('channel_type', sa.String(), nullable=True))
    op.add_column('collab_channel', sa.Column('created_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'collab_channel', 'user', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_driver_user_id'), 'driver', type_='foreignkey')
    op.create_foreign_key(None, 'driver', 'user', ['user_id'], ['id'])
    op.create_index(op.f('ix_fleet_maintenance_forecast_basis_event_id'), 'fleet_maintenance_forecast', ['basis_event_id'], unique=False)
    op.add_column('fueltransaction', sa.Column('truck_id', sa.String(), nullable=True))
    op.add_column('fueltransaction', sa.Column('load_id', sa.String(), nullable=True))
    op.add_column('fueltransaction', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('fueltransaction', sa.Column('external_source', sa.String(), nullable=True))
    op.add_column('fueltransaction', sa.Column('price_per_gallon', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('fueltransaction', sa.Column('status', sa.String(), nullable=True))
    op.add_column('fueltransaction', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_fueltransaction_external_id'), 'fueltransaction', ['external_id'], unique=False)
    op.create_index(op.f('ix_fueltransaction_load_id'), 'fueltransaction', ['load_id'], unique=False)
    op.create_index(op.f('ix_fueltransaction_truck_id'), 'fueltransaction', ['truck_id'], unique=False)
    op.drop_index(op.f('ix_worker_gusto_id'), table_name='worker')
    op.create_unique_constraint(None, 'worker', ['gusto_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker', type_='unique')
    op.create_index(op.f('ix_worker_gusto_id'), 'worker', ['gusto_id'], unique=True)
    op.drop_index(op.f('ix_fueltransaction_truck_id'), table_name='fueltransaction')
    op.drop_index(op.f('ix_fueltransaction_load_id'), table_name='fueltransaction')
    op.drop_index(op.f('ix_fueltransaction_external_id'), table_name='fueltransaction')
    op.drop_column('fueltransaction', 'posted_at')
    op.drop_column('fueltransaction', 'status')
    op.drop_column('fueltransaction', 'price_per_gallon')
    op.drop_column('fueltransaction', 'external_source')
    op.drop_column('fueltransaction', 'external_id')
    op.drop_column('fueltransaction', 'load_id')
    op.drop_column('fueltransaction', 'truck_id')
    op.drop_index(op.f('ix_fleet_maintenance_forecast_basis_event_id'), table_name='fleet_maintenance_forecast')
    op.drop_constraint(None, 'driver', type_='foreignkey')
    op.create_foreign_key(op.f('fk_driver_user_id'), 'driver', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'collab_channel', type_='foreignkey')
    op.drop_column('collab_channel', 'created_by')
    op.drop_column('collab_channel', 'channel_type')
    op.drop_index(op.f('ix_collab_channel_participant_user_id'), table_name='collab_channel_participant')
    op.drop_index(op.f('ix_collab_channel_participant_driver_id'), table_name='collab_channel_participant')
    op.drop_index(op.f('ix_collab_channel_participant_channel_id'), table_name='collab_channel_participant')
    op.drop_table('collab_channel_participant')
    # ### end Alembic commands ###

