"""Add driver tracking fields to loads

Revision ID: 7c9362e64b1a
Revises: 27da85cbf832
Create Date: 2025-12-14 11:50:49.529739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9362e64b1a'
down_revision = '27da85cbf832'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_stripe_invoice_company_id'), table_name='billing_stripe_invoice')
    op.drop_index(op.f('ix_billing_stripe_invoice_stripe_invoice_id'), table_name='billing_stripe_invoice')
    op.drop_table('billing_stripe_invoice')
    op.drop_index(op.f('ix_billing_stripe_webhook_event_event_type'), table_name='billing_stripe_webhook_event')
    op.drop_index(op.f('ix_billing_stripe_webhook_event_stripe_event_id'), table_name='billing_stripe_webhook_event')
    op.drop_table('billing_stripe_webhook_event')
    op.drop_index(op.f('ix_billing_subscription_addon_stripe_subscription_id'), table_name='billing_subscription_addon')
    op.drop_index(op.f('ix_billing_subscription_addon_subscription_id'), table_name='billing_subscription_addon')
    op.drop_table('billing_subscription_addon')
    op.drop_index(op.f('ix_billing_subscription_company_id'), table_name='billing_subscription')
    op.drop_index(op.f('ix_billing_subscription_stripe_customer_id'), table_name='billing_subscription')
    op.drop_index(op.f('ix_billing_subscription_stripe_subscription_id'), table_name='billing_subscription')
    op.drop_table('billing_subscription')
    op.drop_index(op.f('ix_background_check_company_id'), table_name='background_check')
    op.drop_index(op.f('ix_background_check_driver_id'), table_name='background_check')
    op.drop_index(op.f('ix_background_check_onboarding_id'), table_name='background_check')
    op.drop_index(op.f('ix_background_check_status'), table_name='background_check')
    op.drop_index(op.f('ix_background_check_type'), table_name='background_check')
    op.drop_table('background_check')
    op.drop_index(op.f('ix_dqf_document_category'), table_name='dqf_document')
    op.drop_index(op.f('ix_dqf_document_company_id'), table_name='dqf_document')
    op.drop_index(op.f('ix_dqf_document_driver_id'), table_name='dqf_document')
    op.drop_index(op.f('ix_dqf_document_expiration'), table_name='dqf_document')
    op.drop_index(op.f('ix_dqf_document_verification'), table_name='dqf_document')
    op.drop_table('dqf_document')
    op.drop_index(op.f('ix_onboarding_workflow_company_id'), table_name='onboarding_workflow')
    op.drop_index(op.f('ix_onboarding_workflow_driver_id'), table_name='onboarding_workflow')
    op.drop_index(op.f('ix_onboarding_workflow_onboarding_token'), table_name='onboarding_workflow')
    op.drop_index(op.f('ix_onboarding_workflow_status'), table_name='onboarding_workflow')
    op.drop_index(op.f('ix_onboarding_workflow_token'), table_name='onboarding_workflow')
    op.drop_index(op.f('ix_onboarding_workflow_worker_id'), table_name='onboarding_workflow')
    op.drop_table('onboarding_workflow')
    op.drop_index(op.f('ix_billing_payment_method_company_id'), table_name='billing_payment_method')
    op.drop_index(op.f('ix_billing_payment_method_stripe_payment_method_id'), table_name='billing_payment_method')
    op.drop_table('billing_payment_method')
    op.drop_constraint(op.f('ai_contexts_company_id_key'), 'ai_contexts', type_='unique')
    op.drop_index(op.f('ix_ai_contexts_company_id'), table_name='ai_contexts')
    op.create_index(op.f('ix_ai_contexts_company_id'), 'ai_contexts', ['company_id'], unique=True)
    op.alter_column('ai_conversations', 'assistant_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'auto'::character varying"))
    op.drop_constraint(op.f('ai_usage_quota_company_id_key'), 'ai_usage_quota', type_='unique')
    op.alter_column('driver', 'phone_carrier',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Phone carrier for email-to-SMS notifications (verizon, att, tmobile, etc.)',
               existing_nullable=True)
    op.drop_index(op.f('ix_driver_phone_carrier'), table_name='driver')
    op.drop_index(op.f('uq_equipment_company_vin'), table_name='fleet_equipment', postgresql_where="((vin IS NOT NULL) AND ((vin)::text <> ''::text))")
    op.add_column('freight_load', sa.Column('driver_id', sa.String(), nullable=True))
    op.add_column('freight_load', sa.Column('truck_id', sa.String(), nullable=True))
    op.add_column('freight_load', sa.Column('pickup_arrival_time', sa.DateTime(), nullable=True))
    op.add_column('freight_load', sa.Column('pickup_arrival_lat', sa.Float(), nullable=True))
    op.add_column('freight_load', sa.Column('pickup_arrival_lng', sa.Float(), nullable=True))
    op.add_column('freight_load', sa.Column('pickup_departure_time', sa.DateTime(), nullable=True))
    op.add_column('freight_load', sa.Column('pickup_departure_lat', sa.Float(), nullable=True))
    op.add_column('freight_load', sa.Column('pickup_departure_lng', sa.Float(), nullable=True))
    op.add_column('freight_load', sa.Column('delivery_arrival_time', sa.DateTime(), nullable=True))
    op.add_column('freight_load', sa.Column('delivery_arrival_lat', sa.Float(), nullable=True))
    op.add_column('freight_load', sa.Column('delivery_arrival_lng', sa.Float(), nullable=True))
    op.add_column('freight_load', sa.Column('delivery_departure_time', sa.DateTime(), nullable=True))
    op.add_column('freight_load', sa.Column('delivery_departure_lat', sa.Float(), nullable=True))
    op.add_column('freight_load', sa.Column('delivery_departure_lng', sa.Float(), nullable=True))
    op.add_column('freight_load', sa.Column('last_known_lat', sa.Float(), nullable=True))
    op.add_column('freight_load', sa.Column('last_known_lng', sa.Float(), nullable=True))
    op.add_column('freight_load', sa.Column('last_location_update', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_freight_load_driver_id'), 'freight_load', ['driver_id'], unique=False)
    op.create_index(op.f('ix_freight_load_truck_id'), 'freight_load', ['truck_id'], unique=False)
    op.create_foreign_key(None, 'freight_load', 'driver', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'freight_load', 'fleet_equipment', ['truck_id'], ['id'])
    op.drop_index(op.f('ix_hq_contract_contract_number'), table_name='hq_contract')
    op.create_unique_constraint(None, 'hq_contract', ['contract_number'])
    op.drop_index(op.f('ix_hq_payout_stripe_payout_id'), table_name='hq_payout')
    op.create_unique_constraint(None, 'hq_payout', ['stripe_payout_id'])
    op.drop_index(op.f('ix_hq_quote_quote_number'), table_name='hq_quote')
    op.create_unique_constraint(None, 'hq_quote', ['quote_number'])
    op.drop_index(op.f('ix_hq_tenant_stripe_customer_id'), table_name='hq_tenant')
    op.create_unique_constraint(None, 'hq_tenant', ['stripe_customer_id'])
    op.create_unique_constraint(None, 'hq_tenant', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hq_tenant', type_='unique')
    op.drop_constraint(None, 'hq_tenant', type_='unique')
    op.create_index(op.f('ix_hq_tenant_stripe_customer_id'), 'hq_tenant', ['stripe_customer_id'], unique=True)
    op.drop_constraint(None, 'hq_quote', type_='unique')
    op.create_index(op.f('ix_hq_quote_quote_number'), 'hq_quote', ['quote_number'], unique=True)
    op.drop_constraint(None, 'hq_payout', type_='unique')
    op.create_index(op.f('ix_hq_payout_stripe_payout_id'), 'hq_payout', ['stripe_payout_id'], unique=True)
    op.drop_constraint(None, 'hq_contract', type_='unique')
    op.create_index(op.f('ix_hq_contract_contract_number'), 'hq_contract', ['contract_number'], unique=True)
    op.drop_constraint(None, 'freight_load', type_='foreignkey')
    op.drop_constraint(None, 'freight_load', type_='foreignkey')
    op.drop_index(op.f('ix_freight_load_truck_id'), table_name='freight_load')
    op.drop_index(op.f('ix_freight_load_driver_id'), table_name='freight_load')
    op.drop_column('freight_load', 'last_location_update')
    op.drop_column('freight_load', 'last_known_lng')
    op.drop_column('freight_load', 'last_known_lat')
    op.drop_column('freight_load', 'delivery_departure_lng')
    op.drop_column('freight_load', 'delivery_departure_lat')
    op.drop_column('freight_load', 'delivery_departure_time')
    op.drop_column('freight_load', 'delivery_arrival_lng')
    op.drop_column('freight_load', 'delivery_arrival_lat')
    op.drop_column('freight_load', 'delivery_arrival_time')
    op.drop_column('freight_load', 'pickup_departure_lng')
    op.drop_column('freight_load', 'pickup_departure_lat')
    op.drop_column('freight_load', 'pickup_departure_time')
    op.drop_column('freight_load', 'pickup_arrival_lng')
    op.drop_column('freight_load', 'pickup_arrival_lat')
    op.drop_column('freight_load', 'pickup_arrival_time')
    op.drop_column('freight_load', 'truck_id')
    op.drop_column('freight_load', 'driver_id')
    op.create_index(op.f('uq_equipment_company_vin'), 'fleet_equipment', ['company_id', 'vin'], unique=True, postgresql_where="((vin IS NOT NULL) AND ((vin)::text <> ''::text))")
    op.create_index(op.f('ix_driver_phone_carrier'), 'driver', ['phone_carrier'], unique=False)
    op.alter_column('driver', 'phone_carrier',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone carrier for email-to-SMS notifications (verizon, att, tmobile, etc.)',
               existing_nullable=True)
    op.create_unique_constraint(op.f('ai_usage_quota_company_id_key'), 'ai_usage_quota', ['company_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ai_conversations', 'assistant_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'auto'::character varying"))
    op.drop_index(op.f('ix_ai_contexts_company_id'), table_name='ai_contexts')
    op.create_index(op.f('ix_ai_contexts_company_id'), 'ai_contexts', ['company_id'], unique=False)
    op.create_unique_constraint(op.f('ai_contexts_company_id_key'), 'ai_contexts', ['company_id'], postgresql_nulls_not_distinct=False)
    op.create_table('billing_payment_method',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payment_type', sa.VARCHAR(), server_default=sa.text("'card'::character varying"), autoincrement=False, nullable=False),
    sa.Column('card_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('stripe_payment_method_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_billing_payment_method_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('billing_payment_method_pkey'))
    )
    op.create_index(op.f('ix_billing_payment_method_stripe_payment_method_id'), 'billing_payment_method', ['stripe_payment_method_id'], unique=True)
    op.create_index(op.f('ix_billing_payment_method_company_id'), 'billing_payment_method', ['company_id'], unique=False)
    op.create_table('onboarding_workflow',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('worker_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('role_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_dot_driver', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('onboarding_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('onboarding_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('completed_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('background_checks_status', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('background_checks_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='onboarding_workflow_company_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='onboarding_workflow_created_by_fkey'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name='onboarding_workflow_driver_id_fkey'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name='onboarding_workflow_worker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='onboarding_workflow_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_onboarding_workflow_worker_id'), 'onboarding_workflow', ['worker_id'], unique=False)
    op.create_index(op.f('ix_onboarding_workflow_token'), 'onboarding_workflow', ['onboarding_token'], unique=False)
    op.create_index(op.f('ix_onboarding_workflow_status'), 'onboarding_workflow', ['status'], unique=False)
    op.create_index(op.f('ix_onboarding_workflow_onboarding_token'), 'onboarding_workflow', ['onboarding_token'], unique=True)
    op.create_index(op.f('ix_onboarding_workflow_driver_id'), 'onboarding_workflow', ['driver_id'], unique=False)
    op.create_index(op.f('ix_onboarding_workflow_company_id'), 'onboarding_workflow', ['company_id'], unique=False)
    op.create_table('dqf_document',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('document_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verification_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('verification_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('dqf_document_company_id_fkey')),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name=op.f('dqf_document_driver_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('dqf_document_uploaded_by_fkey')),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], name=op.f('dqf_document_verified_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dqf_document_pkey'))
    )
    op.create_index(op.f('ix_dqf_document_verification'), 'dqf_document', ['verification_status'], unique=False)
    op.create_index(op.f('ix_dqf_document_expiration'), 'dqf_document', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_dqf_document_driver_id'), 'dqf_document', ['driver_id'], unique=False)
    op.create_index(op.f('ix_dqf_document_company_id'), 'dqf_document', ['company_id'], unique=False)
    op.create_index(op.f('ix_dqf_document_category'), 'dqf_document', ['document_category'], unique=False)
    op.create_table('background_check',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('onboarding_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('check_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provider_reference_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject_cdl_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject_cdl_state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('subject_dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('has_violations', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('violation_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('violation_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('billed_to_company', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('billing_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('background_check_company_id_fkey')),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name=op.f('background_check_driver_id_fkey')),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboarding_workflow.id'], name=op.f('background_check_onboarding_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('background_check_pkey'))
    )
    op.create_index(op.f('ix_background_check_type'), 'background_check', ['check_type'], unique=False)
    op.create_index(op.f('ix_background_check_status'), 'background_check', ['status'], unique=False)
    op.create_index(op.f('ix_background_check_onboarding_id'), 'background_check', ['onboarding_id'], unique=False)
    op.create_index(op.f('ix_background_check_driver_id'), 'background_check', ['driver_id'], unique=False)
    op.create_index(op.f('ix_background_check_company_id'), 'background_check', ['company_id'], unique=False)
    op.create_table('billing_subscription',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'trialing'::character varying"), autoincrement=False, nullable=False),
    sa.Column('subscription_type', sa.VARCHAR(), server_default=sa.text("'self_serve'::character varying"), autoincrement=False, nullable=False),
    sa.Column('billing_cycle', sa.VARCHAR(), server_default=sa.text("'monthly'::character varying"), autoincrement=False, nullable=False),
    sa.Column('truck_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('base_price_per_truck', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('49.00'), autoincrement=False, nullable=False),
    sa.Column('total_monthly_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False),
    sa.Column('trial_ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('trial_days_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_period_start', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('current_period_end', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('canceled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_billing_subscription_company_id'),
    sa.PrimaryKeyConstraint('id', name='billing_subscription_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_billing_subscription_stripe_subscription_id'), 'billing_subscription', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_billing_subscription_stripe_customer_id'), 'billing_subscription', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_subscription_company_id'), 'billing_subscription', ['company_id'], unique=True)
    op.create_table('billing_subscription_addon',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('monthly_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('employee_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('per_employee_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('has_trial', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('activated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscription.id'], name=op.f('fk_billing_subscription_addon_subscription_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('billing_subscription_addon_pkey'))
    )
    op.create_index(op.f('ix_billing_subscription_addon_subscription_id'), 'billing_subscription_addon', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_subscription_addon_stripe_subscription_id'), 'billing_subscription_addon', ['stripe_subscription_id'], unique=False)
    op.create_table('billing_stripe_webhook_event',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stripe_event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('billing_stripe_webhook_event_pkey'))
    )
    op.create_index(op.f('ix_billing_stripe_webhook_event_stripe_event_id'), 'billing_stripe_webhook_event', ['stripe_event_id'], unique=True)
    op.create_index(op.f('ix_billing_stripe_webhook_event_event_type'), 'billing_stripe_webhook_event', ['event_type'], unique=False)
    op.create_table('billing_stripe_invoice',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_due', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('invoice_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('invoice_pdf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stripe_invoice_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('line_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_billing_stripe_invoice_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('billing_stripe_invoice_pkey'))
    )
    op.create_index(op.f('ix_billing_stripe_invoice_stripe_invoice_id'), 'billing_stripe_invoice', ['stripe_invoice_id'], unique=True)
    op.create_index(op.f('ix_billing_stripe_invoice_company_id'), 'billing_stripe_invoice', ['company_id'], unique=False)
    # ### end Alembic commands ###

