"""Add HQ Deal and Subscription tables

Revision ID: ca7f01f6a392
Revises: 20251225_fix_cols
Create Date: 2025-12-25 23:17:02.133112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7f01f6a392'
down_revision = '20251225_fix_cols'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hq_subscription',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscription_number', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'cancelled', 'past_due', 'trialing', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_interval', sa.Enum('monthly', 'annual', name='billinginterval'), nullable=False),
    sa.Column('monthly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_mrr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('setup_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('setup_fee_paid', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('truck_limit', sa.String(), nullable=True),
    sa.Column('user_limit', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['hq_employee.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['hq_tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hq_subscription_deal_id'), 'hq_subscription', ['deal_id'], unique=False)
    op.create_index(op.f('ix_hq_subscription_status'), 'hq_subscription', ['status'], unique=False)
    op.create_index(op.f('ix_hq_subscription_subscription_number'), 'hq_subscription', ['subscription_number'], unique=True)
    op.create_index(op.f('ix_hq_subscription_tenant_id'), 'hq_subscription', ['tenant_id'], unique=False)
    op.create_table('hq_deal',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deal_number', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_title', sa.String(), nullable=True),
    sa.Column('stage', sa.Enum('lead', 'contacted', 'qualified', 'demo', 'closing', 'won', 'lost', name='dealstage'), nullable=False),
    sa.Column('probability', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_mrr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_setup_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_trucks', sa.String(), nullable=True),
    sa.Column('estimated_close_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('referral', 'website', 'cold_call', 'partner', 'trade_show', 'linkedin', 'fmcsa', 'other', name='dealsource'), nullable=False),
    sa.Column('assigned_sales_rep_id', sa.String(), nullable=True),
    sa.Column('next_follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('dot_number', sa.String(), nullable=True),
    sa.Column('mc_number', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('carrier_type', sa.String(), nullable=True),
    sa.Column('lost_reason', sa.String(), nullable=True),
    sa.Column('competitor', sa.String(), nullable=True),
    sa.Column('won_at', sa.DateTime(), nullable=True),
    sa.Column('lost_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_sales_rep_id'], ['hq_employee.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['hq_employee.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['hq_subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hq_deal_assigned_sales_rep_id'), 'hq_deal', ['assigned_sales_rep_id'], unique=False)
    op.create_index(op.f('ix_hq_deal_company_name'), 'hq_deal', ['company_name'], unique=False)
    op.create_index(op.f('ix_hq_deal_contact_email'), 'hq_deal', ['contact_email'], unique=False)
    op.create_index(op.f('ix_hq_deal_deal_number'), 'hq_deal', ['deal_number'], unique=True)
    op.create_index(op.f('ix_hq_deal_dot_number'), 'hq_deal', ['dot_number'], unique=False)
    op.create_index(op.f('ix_hq_deal_mc_number'), 'hq_deal', ['mc_number'], unique=False)
    op.create_index(op.f('ix_hq_deal_stage'), 'hq_deal', ['stage'], unique=False)
    op.create_index(op.f('ix_hq_deal_state'), 'hq_deal', ['state'], unique=False)
    op.create_table('hq_subscription_rate_change',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('previous_mrr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_mrr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['hq_employee.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['hq_subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hq_subscription_rate_change_subscription_id'), 'hq_subscription_rate_change', ['subscription_id'], unique=False)
    op.create_table('hq_deal_activity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('from_stage', sa.String(), nullable=True),
    sa.Column('to_stage', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['hq_employee.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['hq_deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hq_deal_activity_deal_id'), 'hq_deal_activity', ['deal_id'], unique=False)
    op.drop_index(op.f('idx_neon_branches_status'), table_name='ai_database_branches')
    op.drop_index(op.f('idx_neon_branches_task'), table_name='ai_database_branches')
    op.drop_index(op.f('ix_ai_database_branches_task_id'), table_name='ai_database_branches')
    op.drop_table('ai_database_branches')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_audit_log_company_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_drayage_terminal_company_id'), table_name='drayage_terminal')
    op.drop_index(op.f('ix_drayage_terminal_port_code'), table_name='drayage_terminal')
    op.drop_index(op.f('ix_drayage_terminal_terminal_code'), table_name='drayage_terminal')
    op.drop_index(op.f('ix_terminal_port'), table_name='drayage_terminal')
    op.drop_table('drayage_terminal')
    op.drop_index(op.f('idx_driver_settlements_driver_date'), table_name='driver_settlements')
    op.drop_index(op.f('idx_driver_settlements_load'), table_name='driver_settlements')
    op.drop_index(op.f('idx_driver_settlements_status'), table_name='driver_settlements')
    op.drop_index(op.f('ix_driver_settlements_company_id'), table_name='driver_settlements')
    op.drop_index(op.f('ix_driver_settlements_driver_id'), table_name='driver_settlements')
    op.drop_index(op.f('ix_driver_settlements_load_id'), table_name='driver_settlements')
    op.drop_index(op.f('ix_driver_settlements_settlement_date'), table_name='driver_settlements')
    op.drop_table('driver_settlements')
    op.drop_index(op.f('idx_approval_requests_agent_type'), table_name='ai_approval_requests')
    op.drop_index(op.f('idx_approval_requests_company_status'), table_name='ai_approval_requests')
    op.drop_index(op.f('idx_approval_requests_urgency'), table_name='ai_approval_requests')
    op.drop_index(op.f('ix_ai_approval_requests_company_id'), table_name='ai_approval_requests')
    op.drop_table('ai_approval_requests')
    op.drop_index(op.f('idx_plaid_transaction_account'), table_name='plaid_transaction')
    op.drop_index(op.f('idx_plaid_transaction_company'), table_name='plaid_transaction')
    op.drop_index(op.f('idx_plaid_transaction_date'), table_name='plaid_transaction')
    op.drop_index(op.f('idx_plaid_transaction_reconciled'), table_name='plaid_transaction')
    op.drop_index(op.f('ix_plaid_transaction_account_id'), table_name='plaid_transaction')
    op.drop_index(op.f('ix_plaid_transaction_company_id'), table_name='plaid_transaction')
    op.drop_index(op.f('ix_plaid_transaction_date'), table_name='plaid_transaction')
    op.drop_index(op.f('ix_plaid_transaction_matched_ledger_entry_id'), table_name='plaid_transaction')
    op.drop_index(op.f('ix_plaid_transaction_transaction_id'), table_name='plaid_transaction')
    op.drop_table('plaid_transaction')
    op.drop_index(op.f('ix_drayage_chassis_usage_chassis_number'), table_name='drayage_chassis_usage')
    op.drop_index(op.f('ix_drayage_chassis_usage_chassis_pool_id'), table_name='drayage_chassis_usage')
    op.drop_index(op.f('ix_drayage_chassis_usage_company_id'), table_name='drayage_chassis_usage')
    op.drop_index(op.f('ix_drayage_chassis_usage_container_id'), table_name='drayage_chassis_usage')
    op.drop_table('drayage_chassis_usage')
    op.drop_index(op.f('ix_drayage_steamship_line_company_id'), table_name='drayage_steamship_line')
    op.drop_index(op.f('ix_drayage_steamship_line_scac_code'), table_name='drayage_steamship_line')
    op.drop_index(op.f('ix_ssl_company_active'), table_name='drayage_steamship_line')
    op.drop_table('drayage_steamship_line')
    op.drop_index(op.f('idx_plaid_account_company'), table_name='plaid_account')
    op.drop_index(op.f('idx_plaid_account_item'), table_name='plaid_account')
    op.drop_index(op.f('ix_plaid_account_account_id'), table_name='plaid_account')
    op.drop_index(op.f('ix_plaid_account_company_id'), table_name='plaid_account')
    op.drop_index(op.f('ix_plaid_account_item_id'), table_name='plaid_account')
    op.drop_table('plaid_account')
    op.drop_index(op.f('ix_drayage_chassis_pool_company_id'), table_name='drayage_chassis_pool')
    op.drop_index(op.f('ix_drayage_chassis_pool_pool_code'), table_name='drayage_chassis_pool')
    op.drop_table('drayage_chassis_pool')
    op.drop_index(op.f('ix_appointment_schedule'), table_name='drayage_appointment')
    op.drop_index(op.f('ix_drayage_appointment_company_id'), table_name='drayage_appointment')
    op.drop_index(op.f('ix_drayage_appointment_container_id'), table_name='drayage_appointment')
    op.drop_index(op.f('ix_drayage_appointment_scheduled_date'), table_name='drayage_appointment')
    op.drop_index(op.f('ix_drayage_appointment_terminal_id'), table_name='drayage_appointment')
    op.drop_table('drayage_appointment')
    op.drop_index(op.f('idx_maintenance_wo_company'), table_name='maintenance_work_orders')
    op.drop_index(op.f('idx_maintenance_wo_equipment_status'), table_name='maintenance_work_orders')
    op.drop_index(op.f('idx_maintenance_wo_priority'), table_name='maintenance_work_orders')
    op.drop_index(op.f('idx_maintenance_wo_scheduled'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_company_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_equipment_id'), table_name='maintenance_work_orders')
    op.drop_table('maintenance_work_orders')
    op.drop_index(op.f('ix_container_company_status'), table_name='drayage_container')
    op.drop_index(op.f('ix_container_lfd'), table_name='drayage_container')
    op.drop_index(op.f('ix_container_ssl'), table_name='drayage_container')
    op.drop_index(op.f('ix_drayage_container_bill_of_lading'), table_name='drayage_container')
    op.drop_index(op.f('ix_drayage_container_booking_number'), table_name='drayage_container')
    op.drop_index(op.f('ix_drayage_container_company_id'), table_name='drayage_container')
    op.drop_index(op.f('ix_drayage_container_container_number'), table_name='drayage_container')
    op.drop_index(op.f('ix_drayage_container_last_free_day'), table_name='drayage_container')
    op.drop_index(op.f('ix_drayage_container_load_id'), table_name='drayage_container')
    op.drop_index(op.f('ix_drayage_container_status'), table_name='drayage_container')
    op.drop_index(op.f('ix_drayage_container_steamship_line_id'), table_name='drayage_container')
    op.drop_index(op.f('ix_drayage_container_terminal_id'), table_name='drayage_container')
    op.drop_table('drayage_container')
    op.drop_index(op.f('ix_dqf_document_company_id'), table_name='dqf_document')
    op.drop_index(op.f('ix_dqf_document_driver_id'), table_name='dqf_document')
    op.drop_table('dqf_document')
    op.drop_index(op.f('idx_plaid_item_company'), table_name='plaid_item')
    op.drop_index(op.f('idx_plaid_item_status'), table_name='plaid_item')
    op.drop_index(op.f('ix_plaid_item_company_id'), table_name='plaid_item')
    op.drop_index(op.f('ix_plaid_item_item_id'), table_name='plaid_item')
    op.drop_table('plaid_item')
    op.drop_index(op.f('ix_onboarding_workflow_company_id'), table_name='onboarding_workflow')
    op.drop_index(op.f('ix_onboarding_workflow_driver_id'), table_name='onboarding_workflow')
    op.drop_index(op.f('ix_onboarding_workflow_onboarding_token'), table_name='onboarding_workflow')
    op.drop_index(op.f('ix_onboarding_workflow_worker_id'), table_name='onboarding_workflow')
    op.drop_table('onboarding_workflow')
    op.drop_index(op.f('ix_drayage_event_company_id'), table_name='drayage_event')
    op.drop_index(op.f('ix_drayage_event_container_id'), table_name='drayage_event')
    op.drop_index(op.f('ix_drayage_event_event_at'), table_name='drayage_event')
    op.drop_index(op.f('ix_drayage_event_event_type'), table_name='drayage_event')
    op.drop_index(op.f('ix_event_container_type'), table_name='drayage_event')
    op.drop_table('drayage_event')
    op.drop_index(op.f('ix_charge_type_status'), table_name='drayage_charge')
    op.drop_index(op.f('ix_drayage_charge_company_id'), table_name='drayage_charge')
    op.drop_index(op.f('ix_drayage_charge_container_id'), table_name='drayage_charge')
    op.drop_table('drayage_charge')
    op.drop_index(op.f('idx_agent_stream_company'), table_name='ai_agent_stream')
    op.drop_index(op.f('idx_agent_stream_task_created'), table_name='ai_agent_stream')
    op.drop_index(op.f('ix_ai_agent_stream_company_id'), table_name='ai_agent_stream')
    op.drop_index(op.f('ix_ai_agent_stream_task_id'), table_name='ai_agent_stream')
    op.drop_table('ai_agent_stream')
    op.drop_index(op.f('ix_background_check_company_id'), table_name='background_check')
    op.drop_index(op.f('ix_background_check_driver_id'), table_name='background_check')
    op.drop_index(op.f('ix_background_check_onboarding_id'), table_name='background_check')
    op.drop_table('background_check')
    op.add_column('banking_account', sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('banking_account', sa.Column('available_balance', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('banking_account', sa.Column('synctera_id', sa.String(), nullable=True))
    op.add_column('banking_account', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('banking_account', sa.Column('routing_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_banking_account_synctera_id'), 'banking_account', ['synctera_id'], unique=True)
    op.drop_column('banking_account', 'total_transfers_sent')
    op.drop_column('banking_account', 'total_transfers_received')
    op.drop_column('banking_account', 'daily_transfer_limit')
    op.drop_column('banking_account', 'monthly_transfer_limit')
    op.drop_index(op.f('idx_ach_recipient_company'), table_name='banking_ach_recipient')
    op.drop_column('banking_ach_recipient', 'email')
    op.drop_column('banking_ach_recipient', 'phone')
    op.drop_column('banking_ach_recipient', 'total_transfers')
    op.drop_column('banking_ach_recipient', 'is_verified')
    op.drop_column('banking_ach_recipient', 'last_used_at')
    op.add_column('banking_application', sa.Column('synctera_business_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_banking_application_synctera_business_id'), 'banking_application', ['synctera_business_id'], unique=False)
    op.add_column('banking_business', sa.Column('synctera_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_banking_business_synctera_id'), 'banking_business', ['synctera_id'], unique=False)
    op.add_column('banking_card', sa.Column('card_form', sa.String(), nullable=True))
    op.add_column('banking_card', sa.Column('synctera_id', sa.String(), nullable=True))
    op.add_column('banking_card', sa.Column('card_product_id', sa.String(), nullable=True))
    op.add_column('banking_card', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_banking_card_synctera_id'), 'banking_card', ['synctera_id'], unique=True)
    op.add_column('banking_customer', sa.Column('kyb_status', sa.String(), nullable=True))
    op.add_column('banking_person', sa.Column('synctera_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_banking_person_synctera_id'), 'banking_person', ['synctera_id'], unique=False)
    op.drop_index(op.f('idx_banking_transaction_reconciled'), table_name='banking_transaction')
    op.drop_column('banking_transaction', 'reconciled')
    op.drop_column('banking_transaction', 'matched_ledger_entry_id')
    op.drop_column('banking_transaction', 'reconciled_at')
    op.alter_column('banking_transfer', 'from_account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('banking_transfer', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('banking_transfer', 'fee_amount',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('banking_transfer', 'initiated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('idx_banking_transfer_company_created'), table_name='banking_transfer')
    op.drop_index(op.f('idx_banking_transfer_from_account'), table_name='banking_transfer')
    op.drop_index(op.f('idx_banking_transfer_type_status'), table_name='banking_transfer')
    op.drop_index(op.f('ix_banking_transfer_created_at'), table_name='banking_transfer')
    op.drop_index(op.f('ix_banking_transfer_initiated_by'), table_name='banking_transfer')
    op.drop_index(op.f('ix_banking_transfer_recipient_id'), table_name='banking_transfer')
    op.drop_index(op.f('ix_banking_transfer_scheduled_date'), table_name='banking_transfer')
    op.drop_index(op.f('ix_banking_transfer_status'), table_name='banking_transfer')
    op.drop_index(op.f('ix_banking_transfer_transfer_type'), table_name='banking_transfer')
    op.drop_index(op.f('ix_banking_transfer_external_id'), table_name='banking_transfer')
    op.create_index(op.f('ix_banking_transfer_external_id'), 'banking_transfer', ['external_id'], unique=True)
    op.drop_constraint(op.f('banking_transfer_initiated_by_fkey'), 'banking_transfer', type_='foreignkey')
    op.drop_constraint(op.f('banking_transfer_recipient_id_fkey'), 'banking_transfer', type_='foreignkey')
    op.create_foreign_key(None, 'banking_transfer', 'banking_account', ['to_account_id'], ['id'])
    op.create_foreign_key(None, 'banking_transfer', 'banking_account', ['from_account_id'], ['id'])
    op.drop_column('banking_transfer', 'completed_at')
    op.drop_index(op.f('driver_preference_embedding_idx'), table_name='driver', postgresql_where='(preference_embedding IS NOT NULL)')
    op.drop_column('driver', 'preference_embedding')
    op.drop_index(op.f('load_route_embedding_idx'), table_name='freight_load', postgresql_where='(route_embedding IS NOT NULL)')
    op.drop_column('freight_load', 'route_embedding')
    op.alter_column('hq_ai_actions', 'entity_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_hq_ai_actions_agent_name'), table_name='hq_ai_actions')
    op.drop_index(op.f('ix_hq_ai_actions_entity_id'), table_name='hq_ai_actions')
    op.drop_index(op.f('ix_hq_ai_actions_status'), table_name='hq_ai_actions')
    op.drop_index(op.f('ix_hq_ai_autonomy_rules_action_type'), table_name='hq_ai_autonomy_rules')
    op.drop_index(op.f('ix_hq_ai_autonomy_rules_agent_name'), table_name='hq_ai_autonomy_rules')
    op.drop_index(op.f('ix_hq_commission_payment_period'), table_name='hq_commission_payment')
    op.drop_index(op.f('ix_hq_commission_payment_status'), table_name='hq_commission_payment')
    op.drop_index(op.f('ix_hq_commission_record_status'), table_name='hq_commission_record')
    op.create_foreign_key(None, 'hq_contract', 'hq_employee', ['assigned_sales_rep_id'], ['id'])
    op.drop_index(op.f('ix_hq_lead_status'), table_name='hq_lead')
    op.drop_index(op.f('ix_hq_lead_activities_activity_type'), table_name='hq_lead_activities')
    op.drop_index(op.f('ix_hq_lead_activities_follow_up_date'), table_name='hq_lead_activities')
    op.drop_index(op.f('ix_hq_opportunity_stage'), table_name='hq_opportunity')
    op.create_foreign_key(None, 'hq_quote', 'hq_employee', ['assigned_sales_rep_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hq_quote', type_='foreignkey')
    op.create_index(op.f('ix_hq_opportunity_stage'), 'hq_opportunity', ['stage'], unique=False)
    op.create_index(op.f('ix_hq_lead_activities_follow_up_date'), 'hq_lead_activities', ['follow_up_date'], unique=False)
    op.create_index(op.f('ix_hq_lead_activities_activity_type'), 'hq_lead_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_hq_lead_status'), 'hq_lead', ['status'], unique=False)
    op.drop_constraint(None, 'hq_contract', type_='foreignkey')
    op.create_index(op.f('ix_hq_commission_record_status'), 'hq_commission_record', ['status'], unique=False)
    op.create_index(op.f('ix_hq_commission_payment_status'), 'hq_commission_payment', ['status'], unique=False)
    op.create_index(op.f('ix_hq_commission_payment_period'), 'hq_commission_payment', ['period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_hq_ai_autonomy_rules_agent_name'), 'hq_ai_autonomy_rules', ['agent_name'], unique=False)
    op.create_index(op.f('ix_hq_ai_autonomy_rules_action_type'), 'hq_ai_autonomy_rules', ['action_type'], unique=False)
    op.create_index(op.f('ix_hq_ai_actions_status'), 'hq_ai_actions', ['status'], unique=False)
    op.create_index(op.f('ix_hq_ai_actions_entity_id'), 'hq_ai_actions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_hq_ai_actions_agent_name'), 'hq_ai_actions', ['agent_name'], unique=False)
    op.alter_column('hq_ai_actions', 'entity_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('freight_load', sa.Column('route_embedding', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('load_route_embedding_idx'), 'freight_load', ['route_embedding'], unique=False, postgresql_where='(route_embedding IS NOT NULL)')
    op.add_column('driver', sa.Column('preference_embedding', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('driver_preference_embedding_idx'), 'driver', ['preference_embedding'], unique=False, postgresql_where='(preference_embedding IS NOT NULL)')
    op.add_column('banking_transfer', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'banking_transfer', type_='foreignkey')
    op.drop_constraint(None, 'banking_transfer', type_='foreignkey')
    op.create_foreign_key(op.f('banking_transfer_recipient_id_fkey'), 'banking_transfer', 'banking_ach_recipient', ['recipient_id'], ['id'])
    op.create_foreign_key(op.f('banking_transfer_initiated_by_fkey'), 'banking_transfer', 'user', ['initiated_by'], ['id'])
    op.drop_index(op.f('ix_banking_transfer_external_id'), table_name='banking_transfer')
    op.create_index(op.f('ix_banking_transfer_external_id'), 'banking_transfer', ['external_id'], unique=False)
    op.create_index(op.f('ix_banking_transfer_transfer_type'), 'banking_transfer', ['transfer_type'], unique=False)
    op.create_index(op.f('ix_banking_transfer_status'), 'banking_transfer', ['status'], unique=False)
    op.create_index(op.f('ix_banking_transfer_scheduled_date'), 'banking_transfer', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_banking_transfer_recipient_id'), 'banking_transfer', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_banking_transfer_initiated_by'), 'banking_transfer', ['initiated_by'], unique=False)
    op.create_index(op.f('ix_banking_transfer_created_at'), 'banking_transfer', ['created_at'], unique=False)
    op.create_index(op.f('idx_banking_transfer_type_status'), 'banking_transfer', ['transfer_type', 'status'], unique=False)
    op.create_index(op.f('idx_banking_transfer_from_account'), 'banking_transfer', ['from_account_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_banking_transfer_company_created'), 'banking_transfer', ['company_id', 'created_at'], unique=False)
    op.alter_column('banking_transfer', 'initiated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('banking_transfer', 'fee_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('banking_transfer', 'amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('banking_transfer', 'from_account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('banking_transaction', sa.Column('reconciled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('banking_transaction', sa.Column('matched_ledger_entry_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('banking_transaction', sa.Column('reconciled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_banking_transaction_reconciled'), 'banking_transaction', ['reconciled'], unique=False)
    op.drop_index(op.f('ix_banking_person_synctera_id'), table_name='banking_person')
    op.drop_column('banking_person', 'synctera_id')
    op.drop_column('banking_customer', 'kyb_status')
    op.drop_index(op.f('ix_banking_card_synctera_id'), table_name='banking_card')
    op.drop_column('banking_card', 'updated_at')
    op.drop_column('banking_card', 'card_product_id')
    op.drop_column('banking_card', 'synctera_id')
    op.drop_column('banking_card', 'card_form')
    op.drop_index(op.f('ix_banking_business_synctera_id'), table_name='banking_business')
    op.drop_column('banking_business', 'synctera_id')
    op.drop_index(op.f('ix_banking_application_synctera_business_id'), table_name='banking_application')
    op.drop_column('banking_application', 'synctera_business_id')
    op.add_column('banking_ach_recipient', sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('banking_ach_recipient', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('banking_ach_recipient', sa.Column('total_transfers', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('banking_ach_recipient', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('banking_ach_recipient', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_ach_recipient_company'), 'banking_ach_recipient', ['company_id', 'is_active'], unique=False)
    op.add_column('banking_account', sa.Column('monthly_transfer_limit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True, comment='Monthly transfer limit (USD)'))
    op.add_column('banking_account', sa.Column('daily_transfer_limit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True, comment='Daily transfer limit (USD)'))
    op.add_column('banking_account', sa.Column('total_transfers_received', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Count of transfers received to this account'))
    op.add_column('banking_account', sa.Column('total_transfers_sent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Count of transfers sent from this account'))
    op.drop_index(op.f('ix_banking_account_synctera_id'), table_name='banking_account')
    op.drop_column('banking_account', 'routing_number')
    op.drop_column('banking_account', 'account_number')
    op.drop_column('banking_account', 'synctera_id')
    op.drop_column('banking_account', 'available_balance')
    op.drop_column('banking_account', 'current_balance')
    op.create_table('background_check',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('onboarding_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('check_type', sa.VARCHAR(length=23), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provider_reference_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject_cdl_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject_cdl_state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('subject_dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('has_violations', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('violation_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('violation_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('billed_to_company', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('billing_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('background_check_company_id_fkey')),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name=op.f('background_check_driver_id_fkey')),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboarding_workflow.id'], name=op.f('background_check_onboarding_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('background_check_pkey'))
    )
    op.create_index(op.f('ix_background_check_onboarding_id'), 'background_check', ['onboarding_id'], unique=False)
    op.create_index(op.f('ix_background_check_driver_id'), 'background_check', ['driver_id'], unique=False)
    op.create_index(op.f('ix_background_check_company_id'), 'background_check', ['company_id'], unique=False)
    op.create_table('ai_agent_stream',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_agent_stream_pkey'))
    )
    op.create_index(op.f('ix_ai_agent_stream_task_id'), 'ai_agent_stream', ['task_id'], unique=False)
    op.create_index(op.f('ix_ai_agent_stream_company_id'), 'ai_agent_stream', ['company_id'], unique=False)
    op.create_index(op.f('idx_agent_stream_task_created'), 'ai_agent_stream', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_agent_stream_company'), 'ai_agent_stream', ['company_id', 'created_at'], unique=False)
    op.create_table('drayage_charge',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('container_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('charge_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('charge_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('charge_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('chargeable_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate_per_day', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('rate_tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('drayage_charge_company_id_fkey')),
    sa.ForeignKeyConstraint(['container_id'], ['drayage_container.id'], name=op.f('drayage_charge_container_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drayage_charge_pkey'))
    )
    op.create_index(op.f('ix_drayage_charge_container_id'), 'drayage_charge', ['container_id'], unique=False)
    op.create_index(op.f('ix_drayage_charge_company_id'), 'drayage_charge', ['company_id'], unique=False)
    op.create_index(op.f('ix_charge_type_status'), 'drayage_charge', ['company_id', 'charge_type', 'status'], unique=False)
    op.create_table('drayage_event',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('container_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('event_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('related_entity_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('related_entity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('drayage_event_company_id_fkey')),
    sa.ForeignKeyConstraint(['container_id'], ['drayage_container.id'], name=op.f('drayage_event_container_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drayage_event_pkey'))
    )
    op.create_index(op.f('ix_event_container_type'), 'drayage_event', ['container_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_drayage_event_event_type'), 'drayage_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_drayage_event_event_at'), 'drayage_event', ['event_at'], unique=False)
    op.create_index(op.f('ix_drayage_event_container_id'), 'drayage_event', ['container_id'], unique=False)
    op.create_index(op.f('ix_drayage_event_company_id'), 'drayage_event', ['company_id'], unique=False)
    op.create_table('onboarding_workflow',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('worker_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('role_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_dot_driver', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('onboarding_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('onboarding_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('completed_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('background_checks_status', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('background_checks_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('onboarding_workflow_company_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('onboarding_workflow_created_by_fkey')),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name=op.f('onboarding_workflow_driver_id_fkey')),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name=op.f('onboarding_workflow_worker_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_workflow_pkey'))
    )
    op.create_index(op.f('ix_onboarding_workflow_worker_id'), 'onboarding_workflow', ['worker_id'], unique=False)
    op.create_index(op.f('ix_onboarding_workflow_onboarding_token'), 'onboarding_workflow', ['onboarding_token'], unique=True)
    op.create_index(op.f('ix_onboarding_workflow_driver_id'), 'onboarding_workflow', ['driver_id'], unique=False)
    op.create_index(op.f('ix_onboarding_workflow_company_id'), 'onboarding_workflow', ['company_id'], unique=False)
    op.create_table('plaid_item',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('institution_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('institution_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sync_cursor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='plaid_item_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='plaid_item_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_plaid_item_item_id'), 'plaid_item', ['item_id'], unique=True)
    op.create_index(op.f('ix_plaid_item_company_id'), 'plaid_item', ['company_id'], unique=False)
    op.create_index(op.f('idx_plaid_item_status'), 'plaid_item', ['status'], unique=False)
    op.create_index(op.f('idx_plaid_item_company'), 'plaid_item', ['company_id'], unique=False)
    op.create_table('dqf_document',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_category', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('document_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verification_status', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('verification_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('dqf_document_company_id_fkey')),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name=op.f('dqf_document_driver_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('dqf_document_uploaded_by_fkey')),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], name=op.f('dqf_document_verified_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dqf_document_pkey'))
    )
    op.create_index(op.f('ix_dqf_document_driver_id'), 'dqf_document', ['driver_id'], unique=False)
    op.create_index(op.f('ix_dqf_document_company_id'), 'dqf_document', ['company_id'], unique=False)
    op.create_table('drayage_container',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('load_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('container_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('container_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('container_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_hazmat', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('hazmat_class', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_overweight', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('gross_weight_lbs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('booking_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bill_of_lading', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('house_bill', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('seal_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('steamship_line_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('ssl_scac', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('terminal_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('port_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('terminal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('vessel_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('voyage_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vessel_eta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('vessel_ata', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('discharge_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_free_day', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('per_diem_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('detention_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('empty_return_by', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pickup_terminal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pickup_appointment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('pickup_scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pickup_actual_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('outgate_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('delivery_appointment_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_actual_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('return_terminal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('return_appointment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('return_scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('return_actual_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ingate_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('chassis_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('chassis_pool_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('chassis_pool_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('chassis_outgate_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('chassis_return_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('holds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hold_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('demurrage_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('demurrage_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('per_diem_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('per_diem_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('detention_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('detention_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('chassis_per_diem_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_accessorial_charges', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('port_raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='drayage_container_company_id_fkey'),
    sa.ForeignKeyConstraint(['load_id'], ['freight_load.id'], name='drayage_container_load_id_fkey'),
    sa.ForeignKeyConstraint(['steamship_line_id'], ['drayage_steamship_line.id'], name='drayage_container_steamship_line_id_fkey'),
    sa.ForeignKeyConstraint(['terminal_id'], ['drayage_terminal.id'], name='drayage_container_terminal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='drayage_container_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_drayage_container_terminal_id'), 'drayage_container', ['terminal_id'], unique=False)
    op.create_index(op.f('ix_drayage_container_steamship_line_id'), 'drayage_container', ['steamship_line_id'], unique=False)
    op.create_index(op.f('ix_drayage_container_status'), 'drayage_container', ['status'], unique=False)
    op.create_index(op.f('ix_drayage_container_load_id'), 'drayage_container', ['load_id'], unique=False)
    op.create_index(op.f('ix_drayage_container_last_free_day'), 'drayage_container', ['last_free_day'], unique=False)
    op.create_index(op.f('ix_drayage_container_container_number'), 'drayage_container', ['container_number'], unique=False)
    op.create_index(op.f('ix_drayage_container_company_id'), 'drayage_container', ['company_id'], unique=False)
    op.create_index(op.f('ix_drayage_container_booking_number'), 'drayage_container', ['booking_number'], unique=False)
    op.create_index(op.f('ix_drayage_container_bill_of_lading'), 'drayage_container', ['bill_of_lading'], unique=False)
    op.create_index(op.f('ix_container_ssl'), 'drayage_container', ['company_id', 'ssl_scac'], unique=False)
    op.create_index(op.f('ix_container_lfd'), 'drayage_container', ['company_id', 'last_free_day'], unique=False)
    op.create_index(op.f('ix_container_company_status'), 'drayage_container', ['company_id', 'status'], unique=False)
    op.create_table('maintenance_work_orders',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('maintenance_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('estimated_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('actual_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('completion_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parts_needed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parts_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('labor_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by_ai', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ai_agent_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('technician_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completion_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_work_orders_pkey'))
    )
    op.create_index(op.f('ix_maintenance_work_orders_equipment_id'), 'maintenance_work_orders', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_company_id'), 'maintenance_work_orders', ['company_id'], unique=False)
    op.create_index(op.f('idx_maintenance_wo_scheduled'), 'maintenance_work_orders', ['scheduled_date', 'status'], unique=False)
    op.create_index(op.f('idx_maintenance_wo_priority'), 'maintenance_work_orders', ['priority', 'status'], unique=False)
    op.create_index(op.f('idx_maintenance_wo_equipment_status'), 'maintenance_work_orders', ['equipment_id', 'status'], unique=False)
    op.create_index(op.f('idx_maintenance_wo_company'), 'maintenance_work_orders', ['company_id', 'created_at'], unique=False)
    op.create_table('drayage_appointment',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('container_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('terminal_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('appointment_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('port_appointment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('port_confirmation_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('port_entry_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('scheduled_window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('scheduled_window_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('shift', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('gate_in_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('gate_out_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_turn_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('truck_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('truck_license', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('driver_license', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_dual_transaction', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('dual_container_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('dual_container_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('port_raw_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('drayage_appointment_company_id_fkey')),
    sa.ForeignKeyConstraint(['container_id'], ['drayage_container.id'], name=op.f('drayage_appointment_container_id_fkey')),
    sa.ForeignKeyConstraint(['terminal_id'], ['drayage_terminal.id'], name=op.f('drayage_appointment_terminal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drayage_appointment_pkey'))
    )
    op.create_index(op.f('ix_drayage_appointment_terminal_id'), 'drayage_appointment', ['terminal_id'], unique=False)
    op.create_index(op.f('ix_drayage_appointment_scheduled_date'), 'drayage_appointment', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_drayage_appointment_container_id'), 'drayage_appointment', ['container_id'], unique=False)
    op.create_index(op.f('ix_drayage_appointment_company_id'), 'drayage_appointment', ['company_id'], unique=False)
    op.create_index(op.f('ix_appointment_schedule'), 'drayage_appointment', ['company_id', 'scheduled_date', 'status'], unique=False)
    op.create_table('drayage_chassis_pool',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('pool_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('provider_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_base_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('api_credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('api_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('per_diem_rate_20', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('per_diem_rate_40', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('per_diem_rate_45', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('per_diem_rate_reefer', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('free_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('split_free_time', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('allowed_terminals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('restricted_steamship_lines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('operating_regions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('billing_contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('billing_portal_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='drayage_chassis_pool_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='drayage_chassis_pool_pkey'),
    sa.UniqueConstraint('company_id', 'pool_code', name='uq_chassis_company_pool', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_drayage_chassis_pool_pool_code'), 'drayage_chassis_pool', ['pool_code'], unique=False)
    op.create_index(op.f('ix_drayage_chassis_pool_company_id'), 'drayage_chassis_pool', ['company_id'], unique=False)
    op.create_table('plaid_account',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('official_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_subtype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mask', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_balance', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('available_balance', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('balance_limit', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ledger_account_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enabled_for_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='plaid_account_company_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['plaid_item.id'], name='plaid_account_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='plaid_account_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_plaid_account_item_id'), 'plaid_account', ['item_id'], unique=False)
    op.create_index(op.f('ix_plaid_account_company_id'), 'plaid_account', ['company_id'], unique=False)
    op.create_index(op.f('ix_plaid_account_account_id'), 'plaid_account', ['account_id'], unique=True)
    op.create_index(op.f('idx_plaid_account_item'), 'plaid_account', ['item_id'], unique=False)
    op.create_index(op.f('idx_plaid_account_company'), 'plaid_account', ['company_id'], unique=False)
    op.create_table('drayage_steamship_line',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scac_code', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('api_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('api_base_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('api_credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('api_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('port_free_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rail_free_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('detention_free_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekend_counts', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('holiday_counts', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('demurrage_rate_tier1', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('demurrage_rate_tier2', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('demurrage_rate_tier3', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('detention_rate_per_day', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('per_diem_rate_20', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('per_diem_rate_40', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('per_diem_rate_45', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('customer_service_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('customer_service_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipment_return_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('demurrage_dispute_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='drayage_steamship_line_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='drayage_steamship_line_pkey'),
    sa.UniqueConstraint('company_id', 'scac_code', name='uq_ssl_company_scac', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_ssl_company_active'), 'drayage_steamship_line', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_drayage_steamship_line_scac_code'), 'drayage_steamship_line', ['scac_code'], unique=False)
    op.create_index(op.f('ix_drayage_steamship_line_company_id'), 'drayage_steamship_line', ['company_id'], unique=False)
    op.create_table('drayage_chassis_usage',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('container_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('chassis_pool_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('chassis_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('chassis_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('chassis_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('outgate_terminal', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('outgate_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ingate_terminal', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ingate_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('free_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chargeable_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate_per_day', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chassis_pool_id'], ['drayage_chassis_pool.id'], name=op.f('drayage_chassis_usage_chassis_pool_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('drayage_chassis_usage_company_id_fkey')),
    sa.ForeignKeyConstraint(['container_id'], ['drayage_container.id'], name=op.f('drayage_chassis_usage_container_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drayage_chassis_usage_pkey'))
    )
    op.create_index(op.f('ix_drayage_chassis_usage_container_id'), 'drayage_chassis_usage', ['container_id'], unique=False)
    op.create_index(op.f('ix_drayage_chassis_usage_company_id'), 'drayage_chassis_usage', ['company_id'], unique=False)
    op.create_index(op.f('ix_drayage_chassis_usage_chassis_pool_id'), 'drayage_chassis_usage', ['chassis_pool_id'], unique=False)
    op.create_index(op.f('ix_drayage_chassis_usage_chassis_number'), 'drayage_chassis_usage', ['chassis_number'], unique=False)
    op.create_table('plaid_transaction',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('merchant_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_primary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_detailed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('authorized_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('posted_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pending', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_channel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location_zip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('matched_ledger_entry_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reconciled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reconciled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reconciled_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('suggested_account_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('suggested_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['plaid_account.id'], name=op.f('plaid_transaction_account_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('plaid_transaction_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plaid_transaction_pkey'))
    )
    op.create_index(op.f('ix_plaid_transaction_transaction_id'), 'plaid_transaction', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_plaid_transaction_matched_ledger_entry_id'), 'plaid_transaction', ['matched_ledger_entry_id'], unique=False)
    op.create_index(op.f('ix_plaid_transaction_date'), 'plaid_transaction', ['date'], unique=False)
    op.create_index(op.f('ix_plaid_transaction_company_id'), 'plaid_transaction', ['company_id'], unique=False)
    op.create_index(op.f('ix_plaid_transaction_account_id'), 'plaid_transaction', ['account_id'], unique=False)
    op.create_index(op.f('idx_plaid_transaction_reconciled'), 'plaid_transaction', ['reconciled'], unique=False)
    op.create_index(op.f('idx_plaid_transaction_date'), 'plaid_transaction', ['date'], unique=False)
    op.create_index(op.f('idx_plaid_transaction_company'), 'plaid_transaction', ['company_id'], unique=False)
    op.create_index(op.f('idx_plaid_transaction_account'), 'plaid_transaction', ['account_id'], unique=False)
    op.create_table('ai_approval_requests',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('urgency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('estimated_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('review_decision', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_approval_requests_pkey'))
    )
    op.create_index(op.f('ix_ai_approval_requests_company_id'), 'ai_approval_requests', ['company_id'], unique=False)
    op.create_index(op.f('idx_approval_requests_urgency'), 'ai_approval_requests', ['urgency', 'status'], unique=False)
    op.create_index(op.f('idx_approval_requests_company_status'), 'ai_approval_requests', ['company_id', 'status'], unique=False)
    op.create_index(op.f('idx_approval_requests_agent_type'), 'ai_approval_requests', ['agent_type', 'status'], unique=False)
    op.create_table('driver_settlements',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('load_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('settlement_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('settlement_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('pay_period_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pay_period_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reference_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name=op.f('driver_settlements_driver_id_fkey')),
    sa.ForeignKeyConstraint(['load_id'], ['freight_load.id'], name=op.f('driver_settlements_load_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_settlements_pkey'))
    )
    op.create_index(op.f('ix_driver_settlements_settlement_date'), 'driver_settlements', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_driver_settlements_load_id'), 'driver_settlements', ['load_id'], unique=False)
    op.create_index(op.f('ix_driver_settlements_driver_id'), 'driver_settlements', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_settlements_company_id'), 'driver_settlements', ['company_id'], unique=False)
    op.create_index(op.f('idx_driver_settlements_status'), 'driver_settlements', ['payment_status', 'settlement_date'], unique=False)
    op.create_index(op.f('idx_driver_settlements_load'), 'driver_settlements', ['load_id'], unique=False)
    op.create_index(op.f('idx_driver_settlements_driver_date'), 'driver_settlements', ['driver_id', 'settlement_date'], unique=False)
    op.create_table('drayage_terminal',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('port_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('terminal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('firms_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('appointment_system', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('appointment_lead_time_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('appointment_window_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dual_transaction_allowed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('same_day_appointments', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('gate_hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('first_shift', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('second_shift', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('third_shift', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('vessel_cutoff_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reefer_cutoff_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hazmat_cutoff_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_turn_time_import', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_turn_time_export', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_turn_time_dual', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dispatch_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('trouble_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gate_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('api_credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('api_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('drayage_terminal_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drayage_terminal_pkey')),
    sa.UniqueConstraint('company_id', 'terminal_code', name=op.f('uq_terminal_company_code'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_terminal_port'), 'drayage_terminal', ['port_code', 'terminal_code'], unique=False)
    op.create_index(op.f('ix_drayage_terminal_terminal_code'), 'drayage_terminal', ['terminal_code'], unique=False)
    op.create_index(op.f('ix_drayage_terminal_port_code'), 'drayage_terminal', ['port_code'], unique=False)
    op.create_index(op.f('ix_drayage_terminal_company_id'), 'drayage_terminal', ['company_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_company_id'), 'audit_log', ['company_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('failure_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('login_attempts_pkey'))
    )
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_table('ai_database_branches',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('neon_branch_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('neon_branch_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('branch_connection_uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('proposed_sql', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sql_executed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('affected_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auditor_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('audit_decision', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('audit_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('merged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_database_branches_pkey'))
    )
    op.create_index(op.f('ix_ai_database_branches_task_id'), 'ai_database_branches', ['task_id'], unique=False)
    op.create_index(op.f('idx_neon_branches_task'), 'ai_database_branches', ['task_id'], unique=False)
    op.create_index(op.f('idx_neon_branches_status'), 'ai_database_branches', ['status', 'created_at'], unique=False)
    op.drop_index(op.f('ix_hq_deal_activity_deal_id'), table_name='hq_deal_activity')
    op.drop_table('hq_deal_activity')
    op.drop_index(op.f('ix_hq_subscription_rate_change_subscription_id'), table_name='hq_subscription_rate_change')
    op.drop_table('hq_subscription_rate_change')
    op.drop_index(op.f('ix_hq_deal_state'), table_name='hq_deal')
    op.drop_index(op.f('ix_hq_deal_stage'), table_name='hq_deal')
    op.drop_index(op.f('ix_hq_deal_mc_number'), table_name='hq_deal')
    op.drop_index(op.f('ix_hq_deal_dot_number'), table_name='hq_deal')
    op.drop_index(op.f('ix_hq_deal_deal_number'), table_name='hq_deal')
    op.drop_index(op.f('ix_hq_deal_contact_email'), table_name='hq_deal')
    op.drop_index(op.f('ix_hq_deal_company_name'), table_name='hq_deal')
    op.drop_index(op.f('ix_hq_deal_assigned_sales_rep_id'), table_name='hq_deal')
    op.drop_table('hq_deal')
    op.drop_index(op.f('ix_hq_subscription_tenant_id'), table_name='hq_subscription')
    op.drop_index(op.f('ix_hq_subscription_subscription_number'), table_name='hq_subscription')
    op.drop_index(op.f('ix_hq_subscription_status'), table_name='hq_subscription')
    op.drop_index(op.f('ix_hq_subscription_deal_id'), table_name='hq_subscription')
    op.drop_table('hq_subscription')
    # ### end Alembic commands ###

