"""Complete AI messenger system with subscriber support

Revision ID: db6fc9883051
Revises: ebec3b6d30cf
Create Date: 2025-10-19 21:13:35.172533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6fc9883051'
down_revision: Union[str, None] = 'ebec3b6d30cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_admin_id', sa.String(), nullable=True),
    sa.Column('subscription_tier', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['primary_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscriber_id', sa.String(), nullable=False),
    sa.Column('ai_source', sa.Enum('annie', 'alex', 'atlas', name='ai_source_enum'), nullable=False),
    sa.Column('function_category', sa.String(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='priority_enum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'dismissed', name='insight_status_enum'), nullable=False),
    sa.Column('target_users', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dismissed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messenger_admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subscriber_id', sa.String(), nullable=False),
    sa.Column('can_manage_announcements', sa.Boolean(), nullable=True),
    sa.Column('can_manage_groups', sa.Boolean(), nullable=True),
    sa.Column('can_moderate_messages', sa.Boolean(), nullable=True),
    sa.Column('can_access_ai_settings', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('subscriber_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'companies', 'subscribers', ['subscriber_id'], ['id'])
    op.add_column('conversations', sa.Column('subscriber_id', sa.String(length=36), nullable=True))
    op.add_column('conversations', sa.Column('ai_source', sa.String(length=20), nullable=True))
    op.add_column('conversations', sa.Column('is_ai_conversation', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('group_name', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('group_description', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('is_announcement', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('announcement_title', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'conversations', 'subscribers', ['subscriber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'announcement_title')
    op.drop_column('conversations', 'is_announcement')
    op.drop_column('conversations', 'group_description')
    op.drop_column('conversations', 'group_name')
    op.drop_column('conversations', 'is_ai_conversation')
    op.drop_column('conversations', 'ai_source')
    op.drop_column('conversations', 'subscriber_id')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'subscriber_id')
    op.drop_table('message_attachments')
    op.drop_table('messenger_admins')
    op.drop_table('ai_insights')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
